### ISSUE TITLE
Taro 3.x版本报错

### ISSUE THREAD

**Issue by wangxiaotao00** [wuyf123/taro-antv-f2#1]
VM185:5 SystemError (appServiceSDKScriptError)
Cannot read property 'mode' of undefined
TypeError: Cannot read property 'mode' of undefined

**Comment by wangxiaotao00** [comment]
(function(){
    delete this.nw;
    this.chrome = null
  })();console.group("Wed Oct 28 2020 20:21:22 GMT+0800 (CST) 渲染层错误")
        console.error("SystemError (appServiceSDKScriptError)\nCannot read property 'mode' of undefined\nTypeError: Cannot read property 'mode' of undefined\n    at http://127.0.0.1:17871/__pageframe__/__dev__/WAWebview.js:2:1772030\n    at g (http://127.0.0.1:17871/__pageframe__/__dev__/WAWebview.js:2:81791)\n    at http://127.0.0.1:17871/__pageframe__/__dev__/WAWebview.js:2:83816\n    at Array.forEach (<anonymous>)\n    at http://127.0.0.1:17871/__pageframe__/__dev__/WAWebview.js:2:83796\n    at http://127.0.0.1:17871/__pageframe__/__dev__/WAWebview.js:2:83548\n    at b (http://127.0.0.1:17871/__pageframe__/__dev__/WAWebview.js:2:83747)\n    at Object.cb (http://127.0.0.1:17871/__pageframe__/__dev__/WAWebview.js:2:85087)\n    at http://127.0.0.1:17871/__pageframe__/__dev__/WAWebview.js:2:71017\n    at Array.forEach (<anonymous>)")
      console.groupEnd()
